### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [WarriorBeat/WarriorBeatApp#7]
hello...

You have a very interesting project and as a logo designer who has a passion to help contribute to open source projects, I want to help create a LOGO for your project...

At the moment, I am already working on some cool idea concepts that represents your project and gives it an identity... Once I am done with the concept, I will update it here so you can give me your opinion about the design and possibly any changes you may want...

Regards...

**Comment by BradenM** [comment]
Appreciate the offer, but we actually already have a logo. Sorry for taking so long to get back to you!
